# Analysis & cleaning of student performance data

## Load the dataset
#### preview the dataset to see what we are working with

In [54]:
import pandas as pd
import numpy as np  # na_values=['None', 'NULL', ''] preventing automatic conversion of 'None', 'NULL', and empty strings to NaN
student_performance_df = pd.read_csv('../data/student_performance.csv' #keep_default_na=False  # preventing automatic conversion of 'None', 'NULL', and empty strings to NaN
)
student_performance_df.head(10)

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No
6,STU0007,Male,18,10,72.7,Master,Yes,No,75,42,No
7,STU0008,Female,15,21,81.7,NaN,Yes,Yes,89,70,Yes
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No
9,STU0010,Female,15,8,95.7,NaN,No,Yes,93,56,Yes

In [55]:
student_performance_df.dtypes

student_id                  str
gender                      str
age                       int64
study_hours_per_week      int64
attendance_rate         float64
parent_education            str
internet_access             str
extracurricular             str
previous_score            int64
final_score               int64
passed                      str
dtype: object

In [56]:
student_performance_df.isna().sum()

student_id                0
gender                    0
age                       0
study_hours_per_week      0
attendance_rate           0
parent_education        117
internet_access           0
extracurricular           0
previous_score            0
final_score               0
passed                    0
dtype: int64

In [57]:
student_performance_df["parent_education"].unique()

<StringArray>
['Bachelor', 'High School', 'Master', nan, 'PhD']
Length: 5, dtype: str

In [ ]:
student_performance_df["parent_education"]=student_performance_df["parent_education"].fillna(student_performance_df["parent_education"].mode()[0])

In [59]:
student_performance_df.isna().sum()

student_id              0
gender                  0
age                     0
study_hours_per_week    0
attendance_rate         0
parent_education        0
internet_access         0
extracurricular         0
previous_score          0
final_score             0
passed                  0
dtype: int64

In [62]:
student_performance_df["parent_education"].unique()

<StringArray>
['Bachelor', 'High School', 'Master', 'PhD']
Length: 4, dtype: str

In [63]:
student_performance_df.head(10)

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No
6,STU0007,Male,18,10,72.7,Master,Yes,No,75,42,No
7,STU0008,Female,15,21,81.7,Master,Yes,Yes,89,70,Yes
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No
9,STU0010,Female,15,8,95.7,Master,No,Yes,93,56,Yes

### Analysis by gender
- Determine the number of students? 
- How many students are males?
- How many students are females

In [17]:
# number of students in the dataset
num_students = student_performance_df.shape[0]
print(f'The number of students in the dataset is: {num_students}')

The number of students in the dataset is: 500

In [18]:
# number of females and males
num_females = student_performance_df[student_performance_df['gender'] == 'Female'].shape[0]
num_males = student_performance_df[student_performance_df['gender'] == 'Male'].shape[0]

print(f'The number of females in the dataset is: {num_females}')
print(f'The number of males in the dataset is: {num_males}')

gender_difference = num_females - num_males
print(f"The female students outnumber the male students by: {gender_difference}.")

The number of females in the dataset is: 273
The number of males in the dataset is: 227
The female students outnumber the male students by: 46.

### Determine the mean, median, max and min age of the students

In [19]:
# determine the mean, median, max and min age of the students
mean_age = student_performance_df['age'].mean()
median_age = student_performance_df['age'].median()
max_age = student_performance_df['age'].max()
min_age = student_performance_df['age'].min()

print(f"The mean age of the students is: {mean_age:.2f}")
print(f"The median age of the students is: {median_age}")
print(f"The maximum age of the students is: {max_age}")
print(f"The minimum age of the students is: {min_age}")

The mean age of the students is: 16.98
The median age of the students is: 17.0
The maximum age of the students is: 19
The minimum age of the students is: 15

### Determine:
- The students with the highest study_hours_per_week
- The students with the lowest study_hours_per_week

In [20]:
# number of students with the highest  study_hours_per_week
max_study_hours = student_performance_df['study_hours_per_week'].max()
students_with_max_study_hours = student_performance_df[student_performance_df['study_hours_per_week'] == max_study_hours]
num_students_with_max_study_hours = students_with_max_study_hours.shape[0]
print(f"The number of students with the highest study hours per week ({max_study_hours} hours) is: {num_students_with_max_study_hours}")

The number of students with the highest study hours per week (30 hours) is: 10

In [21]:
min_study_hours = student_performance_df['study_hours_per_week'].min()
students_with_min_study_hours = student_performance_df[student_performance_df['study_hours_per_week'] == min_study_hours]
num_students_with_min_study_hours = students_with_min_study_hours.shape[0]
print(f"The number of students with the lowest study hours per week ({min_study_hours} hours) is: {num_students_with_min_study_hours}")

The number of students with the lowest study hours per week (2 hours) is: 22

### Determine
- Among the students who studied for long hours show how many passed and failed?
- Among the students who studied for short hours show how many passed and failed?

In [22]:
# Split students into long and short study hours groups
median_study_hours = student_performance_df['study_hours_per_week'].median()

long_hours_students = student_performance_df[student_performance_df['study_hours_per_week'] >= median_study_hours]
short_hours_students = student_performance_df[student_performance_df['study_hours_per_week'] < median_study_hours]

# Count pass/fail for long study hours group
long_passed = (long_hours_students['passed'] == 'Yes').sum()
long_failed = (long_hours_students['passed'] == 'No').sum()

print(f"\nStudents with >= {median_study_hours:.1f} hours/week (Long Study Hours):")
print(f"  Passed: {long_passed}")
print(f"  Failed: {long_failed}")
print(f"  Pass Rate: {(long_passed / (long_passed + long_failed) * 100):.1f}%")

# Count pass/fail for short study hours group
short_passed = (short_hours_students['passed'] == 'Yes').sum()
short_failed = (short_hours_students['passed'] == 'No').sum()

print(f"\nStudents with < {median_study_hours:.1f} hours/week (Short Study Hours):")
print(f"  Passed: {short_passed}")
print(f"  Failed: {short_failed}")
print(f"  Pass Rate: {(short_passed / (short_passed + short_failed) * 100):.1f}%")

Students with >= 15.0 hours/week (Long Study Hours):
  Passed: 236
  Failed: 15
  Pass Rate: 94.0%

Students with < 15.0 hours/week (Short Study Hours):
  Passed: 87
  Failed: 162
  Pass Rate: 34.9%

### Determine performance by Gender

In [23]:
female_passed = student_performance_df[student_performance_df['passed'] == 'Yes']['gender'] == 'Female'
female_failed = student_performance_df[student_performance_df['passed'] == 'No']['gender'] == 'Female'

male_passed = student_performance_df[student_performance_df['passed'] == 'Yes']['gender'] == 'Male'
male_failed = student_performance_df[student_performance_df['passed'] == 'No']['gender'] == 'Male'


print(f"\nNumber of female students who passed: {female_passed.sum()}")
print(f"Number of female students who failed: {female_failed.sum()}")
print(f"Number of male students who passed: {male_passed.sum()}")
print(f"Number of male students who failed: {male_failed.sum()}")

Number of female students who passed: 174
Number of female students who failed: 99
Number of male students who passed: 149
Number of male students who failed: 78

### Determine
- Students who had internet access and their performance
- Students whose parents had bachelors, phd and highschool and their performance
- students who took part in extracurricular activites and their perfomance

In [9]:
# students with internet access at home and their performance
student_passed_with_internet = student_performance_df[student_performance_df['passed'] == 'Yes']['internet_access'] == 'Yes'
student_failed_without_internet = student_performance_df[student_performance_df['passed'] == 'No']['internet_access'] == 'No'
student_passed_without_internet = student_performance_df[student_performance_df['passed'] == 'Yes']['internet_access'] == 'No'
student_failed_with_internet = student_performance_df[student_performance_df['passed'] == 'No']['internet_access'] == 'Yes'

print(f"\nNumber of students with internet access at home who passed: {student_passed_with_internet.sum()}")
print(f"Number of students without internet access at home who failed: {student_failed_without_internet.sum()}")
print(f"Number of students with internet access at home who failed: {student_failed_with_internet.sum()}")
print(f"Number of students without internet access at home who passed: {student_passed_without_internet.sum()}")

Number of students with internet access at home who passed: 167
Number of students without internet access at home who failed: 90
Number of students with internet access at home who failed: 87
Number of students without internet access at home who passed: 156

In [26]:
# parental education level and student performance
#parental_none_student_passed = student_performance_df[student_performance_df['passed'] == 'Yes']['parent_education'] == 'None'
#parental_none_student_failed = student_performance_df[student_performance_df['passed'] == 'No']['parent_education'] ==  'None'
parental_Highschool_student_passed = student_performance_df[student_performance_df['passed'] == 'Yes']['parent_education'] == 'High School'
parental_Highschool_student_failed = student_performance_df[student_performance_df['passed'] == 'No']['parent_education'] == 'High School'
parental_bachelor_student_passed = student_performance_df[student_performance_df['passed'] == 'Yes']['parent_education'] == 'Bachelor'
parental_bachelor_student_failed = student_performance_df[student_performance_df['passed'] == 'No']['parent_education'] == 'Bachelor'
parental_master_student_passed = student_performance_df[student_performance_df['passed'] == 'Yes']['parent_education'] == 'Master'
parental_master_student_failed = student_performance_df[student_performance_df['passed'] == 'No']['parent_education'] == 'Master'
parental_PhD_student_passed = student_performance_df[student_performance_df['passed'] == 'Yes']['parent_education'] == 'PhD'
parental_PhD_student_failed = student_performance_df[student_performance_df['passed'] == 'No']['parent_education'] == 'PhD'

#print(f"\nNumber of students with parents having not specified education who passed: {parental_none_student_passed.sum()}")
#print(f"Number of students with parents having not specified education who failed: {parental_none_student_failed.sum()}")
print(f"Number of students with parents having high school education who passed: {parental_Highschool_student_passed.sum()}")
print(f"Number of students with parents having high school education who failed: {parental_Highschool_student_failed.sum()}")
print(f"Number of students with parents having bachelor education who passed: {parental_bachelor_student_passed.sum()}")
print(f"Number of students with parents having bachelor education who failed: {parental_bachelor_student_failed.sum()}")
print(f"Number of students with parents having master education who passed: {parental_master_student_passed.sum()}")
print(f"Number of students with parents having master education who failed: {parental_master_student_failed.sum()}")
print(f"Number of students with parents having PhD education who passed: {parental_PhD_student_passed.sum()}")
print(f"Number of students with parents having PhD education who failed: {parental_PhD_student_failed.sum()}")

Number of students with parents having high school education who passed: 67
Number of students with parents having high school education who failed: 28
Number of students with parents having bachelor education who passed: 52
Number of students with parents having bachelor education who failed: 45
Number of students with parents having master education who passed: 145
Number of students with parents having master education who failed: 72
Number of students with parents having PhD education who passed: 59
Number of students with parents having PhD education who failed: 32

In [27]:
# Extra curricular activities and student performance
student_passed_with_extracurricular = student_performance_df[student_performance_df['passed'] == 'Yes']['extracurricular'] == 'Yes'
student_failed_with_extracurricular = student_performance_df[student_performance_df['passed'] == 'No']['extracurricular'] == 'Yes'
student_passed_without_extracurricular = student_performance_df[student_performance_df['passed'] == 'Yes']['extracurricular'] == 'No'
student_failed_without_extracurricular = student_performance_df[student_performance_df['passed'] == 'No']['extracurricular'] == 'No'

print(f"\nNumber of students with extracurricular activities who passed: {student_passed_with_extracurricular.sum()}")
print(f"Number of students with extracurricular activities who failed: {student_failed_with_extracurricular.sum()}")
print(f"Number of students without extracurricular activities who passed: {student_passed_without_extracurricular.sum()}")
print(f"Number of students without extracurricular activities who failed: {student_failed_without_extracurricular.sum()}")

Number of students with extracurricular activities who passed: 163
Number of students with extracurricular activities who failed: 84
Number of students without extracurricular activities who passed: 160
Number of students without extracurricular activities who failed: 93

### Using Numpy
- Determine the average score of the previous_score and final_score.
- Determine the standard deviation of the previous_score and final_score.

In [28]:
# determine the mean score of students for previous scores using numpy
mean_previous_score = np.mean(student_performance_df['previous_score'])
print(f"The mean previous score of the students is: {mean_previous_score:.2f}")

# determine the mean score of students for final scores using numpy
mean_final_score = np.mean(student_performance_df['final_score'])
print(f"The mean final score of the students is: {mean_final_score:.2f}")

# determine the standard deviation of students for previous scores using numpy
std_previous_score = np.std(student_performance_df['previous_score'])
print(f"The standard deviation of previous scores of the students is: {std_previous_score:.2f}")

# determine the standard deviation of students for final scores using numpy
std_final_score = np.std(student_performance_df['final_score'])
print(f"The standard deviation of final scores of the students is: {std_final_score:.2f}")

# determine the max score of students for previous scores using numpy
max_previous_score = np.max(student_performance_df['previous_score'])
print(f"The max previous score of the students is: {max_previous_score:.2f}")

# determine the max score of students for final scores using numpy
max_final_score = np.max(student_performance_df['final_score'])
print(f"The max final score of the students is: {max_final_score:.2f}")

# determine the min score of students for previous scores using numpy
min_previous_score = np.min(student_performance_df['previous_score'])
print(f"The min previous score of the students is: {min_previous_score:.2f}")

# determine the min score of students for final scores using numpy
min_final_score = np.min(student_performance_df['final_score'])
print(f"The min final score of the students is: {min_final_score:.2f}")

The mean previous score of the students is: 62.99
The mean final score of the students is: 55.98
The standard deviation of previous scores of the students is: 18.92
The standard deviation of final scores of the students is: 15.36
The max previous score of the students is: 95.00
The max final score of the students is: 95.00
The min previous score of the students is: 30.00
The min final score of the students is: 20.00

## Using Pandas

In [30]:
# determine the mean score of students for previous scores 
mean_students_previous_score = student_performance_df['previous_score'].mean()
print(f"The mean previous score of the students is: {mean_students_previous_score:.2f}")

# determine the mean score of students for final scores
mean_students_final_score = student_performance_df['final_score'].mean()
print(f"The mean final score of the students is: {mean_students_final_score:.2f}")

# determine standard deviation of students for previous scores
std_students_previous_score = student_performance_df['previous_score'].std()
print(f"The standard deviation of previous scores of the students is: {std_students_previous_score:.2f}")

# determine standard deviation of students for final scores
std_students_final_score = student_performance_df['final_score'].std()
print(f"The standard deviation of final scores of the students is: {std_students_final_score:.2f}")

# determine the max score of students for previous scores
max_students_previous_score = student_performance_df['previous_score'].max()
print(f"The max previous score of the students is: {max_students_previous_score:.2f}")

# determine the max score of students for final scores
max_students_final_score = student_performance_df['final_score'].max()
print(f"The max final score of the students is: {max_students_final_score:.2f}")

# determine the min score of students for previous scores
min_students_previous_score = student_performance_df['previous_score'].min()
print(f"The min previous score of the students is: {min_students_previous_score:.2f}")

# determine the min score of students for final scores
min_students_final_score = student_performance_df['final_score'].min()
print(f"The min final score of the students is: {min_students_final_score:.2f}")

The mean previous score of the students is: 62.99
The mean final score of the students is: 55.98
The standard deviation of previous scores of the students is: 18.94
The standard deviation of final scores of the students is: 15.37
The max previous score of the students is: 95.00
The max final score of the students is: 95.00
The min previous score of the students is: 30.00
The min final score of the students is: 20.00

### Determine:
- How many student that scored below average, average & above average in previous and final score?

#### Previous test

In [31]:
# number of students with previous score above 80 (above average)
num_students_above_average_in_previous_score = student_performance_df[student_performance_df['previous_score'] > 80].shape[0]
print(f"The number of students with previous score above 80 is: {num_students_above_average_in_previous_score}")

# number of students with 70-79 previous score (average)
num_students_average_in_previous_score = student_performance_df[(student_performance_df['previous_score'] >= 70) & (student_performance_df['previous_score'] < 80)].shape[0]
print(f"The number of students with previous score between 70 and 79 is: {num_students_average_in_previous_score}")

# number of students with previous score below 70 (below average)
num_students_below_average_in_previous_score = student_performance_df[student_performance_df['previous_score'] < 70].shape[0]
print(f"The number of students with previous score below 70 is: {num_students_below_average_in_previous_score}")

The number of students with previous score above 80 is: 121
The number of students with previous score between 70 and 79 is: 74
The number of students with previous score below 70 is: 303

#### Final score

In [32]:
# number of student with final score above 80 (above average)
num_students_above_average_in_final_score = student_performance_df[student_performance_df['final_score'] > 80].shape[0]
print(f"The number of students with final score above 80 is: {num_students_above_average_in_final_score}")

# number of students with 70-79 final score (average)
num_students_average_in_final_score = student_performance_df[(student_performance_df['final_score'] <= 70) & (student_performance_df['final_score'] < 80)].shape[0]
print(f"The number of students with final score between 70 and 79 is: {num_students_average_in_final_score}")

# number of students with final score below 70 (below average)
num_students_below_average_in_final_score = student_performance_df[student_performance_df['final_score'] < 70].shape[0]
print(f"The number of students with final score below 70 is: {num_students_below_average_in_final_score}")

The number of students with final score above 80 is: 21
The number of students with final score between 70 and 79 is: 398
The number of students with final score below 70 is: 385

### Correlation of variables

This code snippet calculates and displays the statistical relationship between two variables in your student performance dataset: previous scores and final scores.

The first line uses pandas' `.corr()` method to compute a **correlation matrix**. This method examines the two columns you've selected—`previous_score` and `final_score`—and calculates how strongly they move together. The correlation matrix is a table showing correlation coefficients between all pairs of columns.

Correlation coefficients range from -1 to 1. A value close to 1 indicates a strong positive relationship (as previous scores increase, final scores tend to increase). A value close to -1 indicates a strong negative relationship (as one increases, the other decreases). A value near 0 suggests little to no linear relationship between the variables.

The `print()` statement displays the correlation matrix in a readable format. The resulting output will show a 2×2 matrix where the diagonal values are always 1 (each variable perfectly correlates with itself), and the off-diagonal values show the correlation between previous and final scores.

This analysis helps you understand whether a student's previous academic performance is a good predictor of their final scores. If the correlation is high (close to 1), previous performance is strongly predictive. If it's low, other factors may be more influential in determining final outcomes.

In [16]:
# correlation between previous scores and final scores
corr_matrix = student_performance_df[['previous_score', 'final_score']].corr()
correlation = corr_matrix.loc['previous_score', 'final_score']

print("\nCorrelation matrix between previous scores and final scores:")
print(corr_matrix)
print(f"\nThe Pearson correlation coefficient is {correlation:.3f}, which indicates a weak positive relationship between previous and final scores.")

Correlation matrix between previous scores and final scores:
                previous_score  final_score
previous_score        1.000000     0.164958
final_score           0.164958     1.000000

The Pearson correlation coefficient is 0.165, which indicates a weak positive relationship between previous and final scores.

In [17]:
# correlation of performance with attendance
attendance_passed = student_performance_df[student_performance_df['passed'] == 'Yes']['attendance_rate'].mean()
attendance_failed = student_performance_df[student_performance_df['passed'] == 'No']['attendance_rate'].mean()
print(f"\nAverage attendance rate for passed students: {attendance_passed:.2f}%")
print(f"Average attendance rate for failed students: {attendance_failed:.2f}%")

Average attendance rate for passed students: 77.94%
Average attendance rate for failed students: 73.53%